# Generated by Django 5.1.6 on 2025-02-10 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
